### Creating Tensors


In [2]:
import torch

points = torch.tensor([4.0, 1.0, 2.0, 3.0, 5.0, 9.0]) # 1-D Tensor
points

tensor([4., 1., 2., 3., 5., 9.])

In [4]:
points[:]


tensor([4., 1., 2., 3., 5., 9.])

In [5]:
points[1:]

tensor([1., 2., 3., 5., 9.])

In [6]:
points[:-1]

tensor([4., 1., 2., 3., 5.])

In [7]:
points[:-1:2]

tensor([4., 2., 5.])

In [30]:
# 2-D Tensor

points = torch.tensor([[1.0,2.0], [3.0, 4.0], [5.0, 6.0]])
print(points)
print("Shape of tensor is {}".format(points.shape))



tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Shape of tensor is torch.Size([3, 2])


In [16]:
points[1:] # All rows except first row, all columns


tensor([[3., 4.],
        [5., 6.]])

In [17]:
points[1:, :] # Same

tensor([[3., 4.],
        [5., 6.]])

In [18]:
points[1:, 0] # All rows except the first row, first column

tensor([3., 5.])

In [31]:
points = points[None] # Same as unsqueeze
points

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]])

In [32]:
print("New shape of points is {}".format(points.shape)) 

New shape of points is torch.Size([1, 3, 2])


In [35]:
points[:, 1:] # All rows except first, all columns

tensor([[[3., 4.],
         [5., 6.]]])

In [37]:
points[:, 1:, 0]

tensor([[3., 5.]])

### More On Tensors 

In [40]:
img_t = torch.randn(3, 5, 5) # shape [channel, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
print("Shape of image is {}".format(img_t.shape))

Shape of image is torch.Size([3, 5, 5])


So sometimes the RGB channels are in dimension 0 (channel, rows, columns), and sometimes they are in dimension 1 (batch, channel, rows, columns). But we can generalize by counting from the end: they are always in dimension –3, the third from the end. The lazy, unweighted mean can thus be written as

In [41]:
img_gray_naive = img_t.mean(-3)
print("Shape after taking channel mean of img_t {}".format(img_gray_naive.shape))
batch_gray_naive = batch_t.mean(-3)
print("Shape after taking channel mean of batch_t {}".format(batch_gray_naive.shape))

Shape after taking channel mean of img_t torch.Size([5, 5])
Shape after taking channel mean of batch_t torch.Size([2, 5, 5])


### Broadcating

In [44]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [45]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

### Naming Channels

In [46]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


..\c10/core/TensorImpl.h:806: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable.


### Numpy To Torch And Back 

In [47]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.12362167, 0.48550708, 0.31346616],
       [0.06958703, 0.87202681, 0.35564815],
       [0.17274318, 0.25416111, 0.26798262],
       [0.97926642, 0.22190905, 0.06998814]])

In [48]:
b = torch.from_numpy(a)
b

tensor([[0.1236, 0.4855, 0.3135],
        [0.0696, 0.8720, 0.3556],
        [0.1727, 0.2542, 0.2680],
        [0.9793, 0.2219, 0.0700]], dtype=torch.float64)

In [50]:
b.short()

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)

In [51]:
# Torch to Numpy
b.numpy()

array([[0.12362167, 0.48550708, 0.31346616],
       [0.06958703, 0.87202681, 0.35564815],
       [0.17274318, 0.25416111, 0.26798262],
       [0.97926642, 0.22190905, 0.06998814]])

In [52]:
# 
b.mul_(3)
b

tensor([[0.3709, 1.4565, 0.9404],
        [0.2088, 2.6161, 1.0669],
        [0.5182, 0.7625, 0.8039],
        [2.9378, 0.6657, 0.2100]], dtype=torch.float64)

In [53]:
a

array([[0.37086502, 1.45652124, 0.94039848],
       [0.20876108, 2.61608043, 1.06694444],
       [0.51822953, 0.76248334, 0.80394786],
       [2.93779927, 0.66572714, 0.20996443]])